numeros = [5,10,25,40,50.6,51.6,80,20]
print(numeros)
numeros.pop()
numeros.pop()
print(numeros)
numeros.insert(6,66)
print(numeros)
numeros.remove(51.6)
print(numeros)
print(len(numeros))
print(sum(numeros))
media = sum(numeros)/len(numeros)
print(media)
numeros.sort()
print(numeros)
numeros.sort(reverse=True)
print(numeros)
print(max(numeros))
print(min(numeros))